// Copyright 2025 Tano Karbou (github: karbou12 / X: @karbou_12)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once
#include "us_version.h"

#ifdef CAPS_WORD_ENABLE
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 3000
#endif

#ifdef CUSTOM_KEY_OVERRIDE_ENABLE
#define USE_UINT16_KEYCODE_FOR_VIAL
#endif

#ifdef POINTING_DEVICE_ENABLE
#define EECONFIG_KB_DATA_SIZE 4
#define EECONFIG_KB_DATA_VERSION US_CONCAT_VER(FKVS(MAJOR), FKVS(MINOR), FKVS(PATCH))
#else
#define EECONFIG_KB_DATA_SIZE 0
#endif

// DATA_MIN_SIZE is used for migration of gravity45 release
#if defined(RGBLIGHT_LAYERS) || defined(CUSTOM_RGBMATRIX)
#define EECONFIG_USER_RGB_DATA_CALC_SIZE 4 * DYNAMIC_KEYMAP_LAYER_COUNT + 1
#else
#define EECONFIG_USER_RGB_DATA_CALC_SIZE 0
#endif

#ifdef OS_DETECTION_ENABLE
#define EECONFIG_USER_OS_DATA_SIZE 5
#else
#define EECONFIG_USER_OS_DATA_SIZE 0
#endif

#define EECONFIG_USER_DATA_CALC_SIZE (EECONFIG_USER_RGB_DATA_CALC_SIZE + EECONFIG_USER_OS_DATA_SIZE)
#define EECONFIG_USER_DATA_SIZE EECONFIG_USER_DATA_CALC_SIZE

#define EECONFIG_USER_DATA_VERSION US_CONCAT_VER(FUVS(MAJOR), FUVS(MINOR), FUVS(PATCH))
