// Copyright 2025 Tano Karbou (github: karbou12 / X: @karbou_12)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define LAYOUT_wrapper(...) LAYOUT(__VA_ARGS__)

#ifndef OS_MAC_BASE
#define OS_MAC_BASE 0
#endif
#ifndef OS_WIN_BASE
#define OS_WIN_BASE 4
#endif

// Mac
#define OS_MAC_RAISE     OS_MAC_BASE + 1
#define OS_MAC_LOWER     OS_MAC_BASE + 2
#define OS_MAC_ADJUST    OS_MAC_BASE + 3

#define OS_MAC_SHORT     LGUI_T

#define OS_MAC_0         KC_P0
#define OS_MAC_1         KC_P1
#define OS_MAC_2         KC_P2
#define OS_MAC_3         KC_P3
#define OS_MAC_4         KC_P4
#define OS_MAC_5         KC_P5
#define OS_MAC_6         KC_P6
#define OS_MAC_7         KC_P7
#define OS_MAC_8         KC_P8
#define OS_MAC_9         KC_P9
#define OS_MAC_PLUS      KC_PPLS
#define OS_MAC_MINUS     KC_PMNS
#define OS_MAC_MULTIPLY  LSFT(KC_8)
#define OS_MAC_DIVIDE    KC_PSLS
#define OS_MAC_EQUAL     KC_PEQL
#define OS_MAC_DOT       KC_PDOT

#define OS_MAC_CAPTURE_1 LSG(KC_3)
#define OS_MAC_CAPTURE_2 LSG(KC_4)
#define OS_MAC_CAPTURE_3 LSG(KC_5)
#define OS_MAC_LOCK      LCG(KC_Q)
#define OS_MAC_DF        DF(WIN(BASE))

#define MAC(x) OS_MAC_ ## x
#define WIN(x) OS_WIN_ ## x

// ==========   QAZ   ==========
// Layer 0  Mac Base
#define MAC_QAZ_BASE_LEFT_TOP     KC_Q,         KC_W,         KC_E,         KC_R,           KC_T
#define MAC_QAZ_BASE_LEFT_MIDDLE  KC_A,         LALT_T(KC_S), LCTL_T(KC_D), LGUI_T(KC_F),   KC_G
#define MAC_QAZ_BASE_LEFT_BOTTOM  LSFT_T(KC_Z), KC_X,         KC_C,         KC_V,           KC_B

#define MAC_QAZ_BASE_RIGHT_TOP    KC_Y,         KC_U,         KC_I,         KC_O,           KC_P
#define MAC_QAZ_BASE_RIGHT_MIDDLE KC_H,         KC_J,         KC_K,         KC_L,           RCTL_T(KC_SCLN)
#define MAC_QAZ_BASE_RIGHT_BOTTOM KC_N,         KC_M,         KC_COMM,      RALT_T(KC_DOT), RSFT_T(KC_SLSH)

#define MAC_QAZ_BASE_LEFT_THUMBS  KC_ESC,         MO(MAC(LOWER)), MAC(SHORT)(KC_TAB)
#define MAC_QAZ_BASE_RIGHT_THUMBS RSFT_T(KC_SPC), MO(MAC(RAISE)), KC_RGUI

// Layer 1  Mac Raise : Numbers and Arrows
#define MAC_QAZ_RAISE_LEFT_TOP     MAC(DIVIDE),    MAC(7),         MAC(8),         MAC(9),          MAC(MINUS)
#define MAC_QAZ_RAISE_LEFT_MIDDLE  MAC(MULTIPLY),  LALT_T(MAC(4)), LCTL_T(MAC(5)), LGUI_T(MAC(6)),  MAC(PLUS)
#define MAC_QAZ_RAISE_LEFT_BOTTOM  LSFT_T(MAC(0)), MAC(1),         MAC(2),         MAC(3),          MAC(EQUAL)

#define MAC_QAZ_RAISE_RIGHT_TOP    KC_NO,          KC_BSPC,        KC_DEL,         KC_TAB,         KC_MINS
#define MAC_QAZ_RAISE_RIGHT_MIDDLE KC_LEFT,        KC_DOWN,        KC_UP,          KC_RIGHT,       KC_ENT
#define MAC_QAZ_RAISE_RIGHT_BOTTOM KC_HOME,        KC_PGDN,        KC_PGUP,        RALT_T(KC_END), KC_RSFT

#define MAC_QAZ_RAISE_LEFT_THUMBS  KC_SPC,       LT(MAC(ADJUST), MAC(DOT)), LGUI_T(KC_BSPC)
#define MAC_QAZ_RAISE_RIGHT_THUMBS KC_NO,        KC_NO,                     KC_NO

// Layer 2  Mac Lower : Symbols
#define MAC_QAZ_LOWER_LEFT_TOP     LSFT(KC_SLSH),  LSFT(KC_QUOT),   LSFT(KC_1),    KC_BSPC,        LSFT(KC_GRAVE)
#define MAC_QAZ_LOWER_LEFT_MIDDLE  LSFT(KC_2),     LALT_T(KC_QUOT), LSFT(KC_4),    KC_DEL,         KC_SLSH
#define MAC_QAZ_LOWER_LEFT_BOTTOM  LSFT_T(KC_ENT), KC_GRAVE,        LSFT(KC_6),    LSFT(KC_BSLS),  KC_BSLS

#define MAC_QAZ_LOWER_RIGHT_TOP    KC_NO,          LSFT(KC_MINS),   LSFT(KC_9),    LSFT(KC_0),     LSFT(KC_5)
#define MAC_QAZ_LOWER_RIGHT_MIDDLE LSFT(KC_3),     KC_NO,           KC_LBRC,       KC_RBRC,        KC_RCTL
#define MAC_QAZ_LOWER_RIGHT_BOTTOM LSFT(KC_7),     KC_NO,           LSFT(KC_LBRC), LSFT(KC_RBRC),  KC_RSFT

#define MAC_QAZ_LOWER_LEFT_THUMBS  KC_SPC,         KC_NO,           KC_NO
#define MAC_QAZ_LOWER_RIGHT_THUMBS RSFT_T(KC_ENT), MO(MAC(ADJUST)), KC_NO

// Layer 3  Mac Adjust : Functions and Mouse
#define MAC_QAZ_ADJUST_LEFT_TOP     KC_MUTE,         KC_F7,         KC_F8,         KC_F9,         KC_F12
#define MAC_QAZ_ADJUST_LEFT_MIDDLE  KC_VOLU,         LALT_T(KC_F4), LCTL_T(KC_F5), LGUI_T(KC_F6), KC_F11
#define MAC_QAZ_ADJUST_LEFT_BOTTOM  LSFT_T(KC_VOLD), KC_F1,         KC_F2,         KC_F3,         KC_F10

#define MAC_QAZ_ADJUST_RIGHT_TOP    MS_WHLL, MS_WHLD, MS_WHLU, MS_WHLR, MAC(CAPTURE_3)
#define MAC_QAZ_ADJUST_RIGHT_MIDDLE MS_LEFT, MS_DOWN, MS_UP,   MS_RGHT, RCTL_T(KC_BRIU)
#define MAC_QAZ_ADJUST_RIGHT_BOTTOM KC_NO,   KC_RGUI, KC_RCTL, KC_RALT, RSFT_T(KC_BRID)

#define MAC_QAZ_ADJUST_LEFT_THUMBS        MAC(LOCK), MAC(DF), KC_NO
#define MAC_QAZ_ADJUST_LEFT_THUMBS_WO_DF  MAC(LOCK), KC_NO,   KC_NO
#define MAC_QAZ_ADJUST_RIGHT_THUMBS       MS_BTN1,   MS_BTN3, MS_BTN2

// ==========   40% QAZ   ==========
// Layer 0  Mac Base
#define MAC_QAZ40_BASE_LEFT_TOP       MAC_QAZ_BASE_LEFT_TOP,    KC_NO
#define MAC_QAZ40_BASE_LEFT_MIDDLE    MAC_QAZ_BASE_LEFT_MIDDLE, KC_NO
#define MAC_QAZ40_BASE_LEFT_BOTTOM    MAC_QAZ_BASE_LEFT_BOTTOM, KC_NO

#define MAC_QAZ40_BASE_RIGHT_TOP      KC_NO, MAC_QAZ_BASE_RIGHT_TOP
#define MAC_QAZ40_BASE_RIGHT_MIDDLE   KC_NO, MAC_QAZ_BASE_RIGHT_MIDDLE
#define MAC_QAZ40_BASE_RIGHT_BOTTOM   KC_NO, MAC_QAZ_BASE_RIGHT_BOTTOM

// Layer 1  Mac Raise : Numbers and Arrows
#define MAC_QAZ40_RAISE_LEFT_TOP      MAC_QAZ_RAISE_LEFT_TOP,    KC_NO
#define MAC_QAZ40_RAISE_LEFT_MIDDLE   MAC_QAZ_RAISE_LEFT_MIDDLE, KC_NO
#define MAC_QAZ40_RAISE_LEFT_BOTTOM   MAC_QAZ_RAISE_LEFT_BOTTOM, KC_NO

#define MAC_QAZ40_RAISE_RIGHT_TOP     KC_NO, MAC_QAZ_RAISE_RIGHT_TOP
#define MAC_QAZ40_RAISE_RIGHT_MIDDLE  KC_NO, MAC_QAZ_RAISE_RIGHT_MIDDLE
#define MAC_QAZ40_RAISE_RIGHT_BOTTOM  KC_NO, MAC_QAZ_RAISE_RIGHT_BOTTOM

// Layer 2  Mac Lower : Symbols
#define MAC_QAZ40_LOWER_LEFT_TOP      MAC_QAZ_LOWER_LEFT_TOP,    KC_NO
#define MAC_QAZ40_LOWER_LEFT_MIDDLE   MAC_QAZ_LOWER_LEFT_MIDDLE, KC_NO
#define MAC_QAZ40_LOWER_LEFT_BOTTOM   MAC_QAZ_LOWER_LEFT_BOTTOM, KC_NO

#define MAC_QAZ40_LOWER_RIGHT_TOP     KC_NO, MAC_QAZ_LOWER_RIGHT_TOP
#define MAC_QAZ40_LOWER_RIGHT_MIDDLE  KC_NO, MAC_QAZ_LOWER_RIGHT_MIDDLE
#define MAC_QAZ40_LOWER_RIGHT_BOTTOM  KC_NO, MAC_QAZ_LOWER_RIGHT_BOTTOM

// Layer 3  Mac Adjust : Functions and Mouse
#define MAC_QAZ40_ADJUST_LEFT_TOP     MAC_QAZ_ADJUST_LEFT_TOP,    MAC(CAPTURE_1)
#define MAC_QAZ40_ADJUST_LEFT_MIDDLE  MAC_QAZ_ADJUST_LEFT_MIDDLE, MAC(CAPTURE_2)
#define MAC_QAZ40_ADJUST_LEFT_BOTTOM  MAC_QAZ_ADJUST_LEFT_BOTTOM, MAC(CAPTURE_3)

#define MAC_QAZ40_ADJUST_RIGHT_TOP    KC_NO, MAC_QAZ_ADJUST_RIGHT_TOP
#define MAC_QAZ40_ADJUST_RIGHT_MIDDLE KC_NO, MAC_QAZ_ADJUST_RIGHT_MIDDLE
#define MAC_QAZ40_ADJUST_RIGHT_BOTTOM KC_NO, MAC_QAZ_ADJUST_RIGHT_BOTTOM

// ==========   40% Normal   ==========
// Layer 0  Mac Base
#define MAC_NOR40_BASE_LEFT_TOP       KC_TAB,  MAC_QAZ_BASE_LEFT_TOP
#define MAC_NOR40_BASE_LEFT_MIDDLE    KC_LCTL, MAC_QAZ_BASE_LEFT_MIDDLE
#define MAC_NOR40_BASE_LEFT_BOTTOM    KC_LSFT, MAC_QAZ_BASE_LEFT_BOTTOM

#define MAC_NOR40_BASE_RIGHT_TOP      MAC_QAZ_BASE_RIGHT_TOP,    KC_BSPC
#define MAC_NOR40_BASE_RIGHT_MIDDLE   MAC_QAZ_BASE_RIGHT_MIDDLE, KC_ENT
#define MAC_NOR40_BASE_RIGHT_BOTTOM   MAC_QAZ_BASE_RIGHT_BOTTOM, KC_RSFT

// Layer 1  Mac Raise : Numbers and Arrows
#define MAC_NOR40_RAISE_LEFT_TOP       KC_TAB,  MAC_QAZ_RAISE_LEFT_TOP
#define MAC_NOR40_RAISE_LEFT_MIDDLE    KC_LCTL, MAC_QAZ_RAISE_LEFT_MIDDLE
#define MAC_NOR40_RAISE_LEFT_BOTTOM    KC_LSFT, MAC_QAZ_RAISE_LEFT_BOTTOM

#define MAC_NOR40_RAISE_RIGHT_TOP      MAC_QAZ_RAISE_RIGHT_TOP,    KC_NO
#define MAC_NOR40_RAISE_RIGHT_MIDDLE   MAC_QAZ_RAISE_RIGHT_MIDDLE, KC_NO
#define MAC_NOR40_RAISE_RIGHT_BOTTOM   MAC_QAZ_RAISE_RIGHT_BOTTOM, KC_NO

// Layer 2  Mac Lower : Symbols
#define MAC_NOR40_LOWER_LEFT_TOP       KC_TAB,  MAC_QAZ_LOWER_LEFT_TOP
#define MAC_NOR40_LOWER_LEFT_MIDDLE    KC_LCTL, MAC_QAZ_LOWER_LEFT_MIDDLE
#define MAC_NOR40_LOWER_LEFT_BOTTOM    KC_LSFT, MAC_QAZ_LOWER_LEFT_BOTTOM

#define MAC_NOR40_LOWER_RIGHT_TOP      MAC_QAZ_LOWER_RIGHT_TOP,    KC_NO
#define MAC_NOR40_LOWER_RIGHT_MIDDLE   MAC_QAZ_LOWER_RIGHT_MIDDLE, KC_NO
#define MAC_NOR40_LOWER_RIGHT_BOTTOM   MAC_QAZ_LOWER_RIGHT_BOTTOM, KC_NO

// Layer 3  Mac Adjust : Functions and Mouse
#define MAC_NOR40_ADJUST_LEFT_TOP       KC_TAB,  MAC_QAZ_ADJUST_LEFT_TOP
#define MAC_NOR40_ADJUST_LEFT_MIDDLE    KC_LCTL, MAC_QAZ_ADJUST_LEFT_MIDDLE
#define MAC_NOR40_ADJUST_LEFT_BOTTOM    KC_LSFT, MAC_QAZ_ADJUST_LEFT_BOTTOM

#define MAC_NOR40_ADJUST_RIGHT_TOP      MAC_QAZ_ADJUST_RIGHT_TOP,    MAC(CAPTURE_1)
#define MAC_NOR40_ADJUST_RIGHT_MIDDLE   MAC_QAZ_ADJUST_RIGHT_MIDDLE, MAC(CAPTURE_2)
#define MAC_NOR40_ADJUST_RIGHT_BOTTOM   MAC_QAZ_ADJUST_RIGHT_BOTTOM, MAC(CAPTURE_3)

// Win
#define OS_WIN_RAISE     OS_WIN_BASE + 1
#define OS_WIN_LOWER     OS_WIN_BASE + 2
#define OS_WIN_ADJUST    OS_WIN_BASE + 3

#define OS_WIN_SHORT LCTL_T

#define OS_WIN_0         KC_0
#define OS_WIN_1         KC_1
#define OS_WIN_2         KC_2
#define OS_WIN_3         KC_3
#define OS_WIN_4         KC_4
#define OS_WIN_5         KC_5
#define OS_WIN_6         KC_6
#define OS_WIN_7         KC_7
#define OS_WIN_8         KC_8
#define OS_WIN_9         KC_9
#define OS_WIN_PLUS      KC_PLUS
#define OS_WIN_MINUS     KC_MINS
#define OS_WIN_MULTIPLY  LSFT(KC_8)
#define OS_WIN_DIVIDE    KC_SLSH
#define OS_WIN_EQUAL     KC_EQL
#define OS_WIN_DOT       KC_DOT

#define OS_WIN_CAPTURE_1 KC_PSCR
#define OS_WIN_CAPTURE_2 LALT(KC_PSCR)
#define OS_WIN_CAPTURE_3 LSG(KC_S)
#define OS_WIN_LOCK      LCA(KC_DEL)
#define OS_WIN_DF        DF(OS_MAC_BASE)

// ==========   QAZ   ==========
// Layer 4  Win Base
#define WIN_QAZ_BASE_LEFT_TOP     MAC_QAZ_BASE_LEFT_TOP
#define WIN_QAZ_BASE_LEFT_MIDDLE  MAC_QAZ_BASE_LEFT_MIDDLE
#define WIN_QAZ_BASE_LEFT_BOTTOM  MAC_QAZ_BASE_LEFT_BOTTOM

#define WIN_QAZ_BASE_RIGHT_TOP    MAC_QAZ_BASE_RIGHT_TOP
#define WIN_QAZ_BASE_RIGHT_MIDDLE MAC_QAZ_BASE_RIGHT_MIDDLE
#define WIN_QAZ_BASE_RIGHT_BOTTOM MAC_QAZ_BASE_RIGHT_BOTTOM

#define WIN_QAZ_BASE_LEFT_THUMBS  KC_ESC,         MO(WIN(LOWER)), WIN(SHORT)(KC_TAB)
#define WIN_QAZ_BASE_RIGHT_THUMBS RSFT_T(KC_SPC), MO(WIN(RAISE)), KC_RGUI

// Layer 5  Win Raise : Numbers and Arrows
#define WIN_QAZ_RAISE_LEFT_TOP     WIN(DIVIDE),    WIN(7),         WIN(8),         WIN(9),           WIN(MINUS)
#define WIN_QAZ_RAISE_LEFT_MIDDLE  WIN(MULTIPLY),  LALT_T(WIN(4)), LCTL_T(WIN(5)), LGUI_T(WIN(6)),   WIN(PLUS)
#define WIN_QAZ_RAISE_LEFT_BOTTOM  LSFT_T(WIN(0)), WIN(1),         WIN(2),         WIN(3),           WIN(EQUAL)

#define WIN_QAZ_RAISE_RIGHT_TOP    MAC_QAZ_RAISE_RIGHT_TOP
#define WIN_QAZ_RAISE_RIGHT_MIDDLE MAC_QAZ_RAISE_RIGHT_MIDDLE
#define WIN_QAZ_RAISE_RIGHT_BOTTOM MAC_QAZ_RAISE_RIGHT_BOTTOM

#define WIN_QAZ_RAISE_LEFT_THUMBS  KC_SPC,       LT(WIN(ADJUST), WIN(DOT)), LGUI_T(KC_BSPC)
#define WIN_QAZ_RAISE_RIGHT_THUMBS MAC_QAZ_RAISE_RIGHT_THUMBS

// Layer 6  Win Lower : Symbols
#define WIN_QAZ_LOWER_LEFT_TOP     MAC_QAZ_LOWER_LEFT_TOP
#define WIN_QAZ_LOWER_LEFT_MIDDLE  MAC_QAZ_LOWER_LEFT_MIDDLE
#define WIN_QAZ_LOWER_LEFT_BOTTOM  MAC_QAZ_LOWER_LEFT_BOTTOM

#define WIN_QAZ_LOWER_RIGHT_TOP    MAC_QAZ_LOWER_RIGHT_TOP
#define WIN_QAZ_LOWER_RIGHT_MIDDLE MAC_QAZ_LOWER_RIGHT_MIDDLE
#define WIN_QAZ_LOWER_RIGHT_BOTTOM MAC_QAZ_LOWER_RIGHT_BOTTOM

#define WIN_QAZ_LOWER_LEFT_THUMBS  MAC_QAZ_LOWER_LEFT_THUMBS
#define WIN_QAZ_LOWER_RIGHT_THUMBS RSFT_T(KC_ENT), MO(WIN(ADJUST)), KC_NO

// Layer 7  Win Adjust : Functions and Mouse
#define WIN_QAZ_ADJUST_LEFT_TOP     MAC_QAZ_ADJUST_LEFT_TOP
#define WIN_QAZ_ADJUST_LEFT_MIDDLE  MAC_QAZ_ADJUST_LEFT_MIDDLE
#define WIN_QAZ_ADJUST_LEFT_BOTTOM  MAC_QAZ_ADJUST_LEFT_BOTTOM

#define WIN_QAZ_ADJUST_RIGHT_TOP    MS_WHLL, MS_WHLD, MS_WHLU, MS_WHLR, WIN(CAPTURE_3)
#define WIN_QAZ_ADJUST_RIGHT_MIDDLE MAC_QAZ_ADJUST_RIGHT_MIDDLE
#define WIN_QAZ_ADJUST_RIGHT_BOTTOM MAC_QAZ_ADJUST_RIGHT_BOTTOM

#define WIN_QAZ_ADJUST_LEFT_THUMBS        WIN(LOCK), WIN(DF), KC_NO
#define WIN_QAZ_ADJUST_LEFT_THUMBS_WO_DF  WIN(LOCK), KC_NO, KC_NO
#define WIN_QAZ_ADJUST_RIGHT_THUMBS       MAC_QAZ_ADJUST_RIGHT_THUMBS

// ==========   40% QAZ   ==========
// Layer 4  Win Base
#define WIN_QAZ40_BASE_LEFT_TOP       WIN_QAZ_BASE_LEFT_TOP,    KC_NO
#define WIN_QAZ40_BASE_LEFT_MIDDLE    WIN_QAZ_BASE_LEFT_MIDDLE, KC_NO
#define WIN_QAZ40_BASE_LEFT_BOTTOM    WIN_QAZ_BASE_LEFT_BOTTOM, KC_NO

#define WIN_QAZ40_BASE_RIGHT_TOP      KC_NO, WIN_QAZ_BASE_RIGHT_TOP
#define WIN_QAZ40_BASE_RIGHT_MIDDLE   KC_NO, WIN_QAZ_BASE_RIGHT_MIDDLE
#define WIN_QAZ40_BASE_RIGHT_BOTTOM   KC_NO, WIN_QAZ_BASE_RIGHT_BOTTOM

// Layer 5  Win Raise : Numbers and Arrows
#define WIN_QAZ40_RAISE_LEFT_TOP      WIN_QAZ_RAISE_LEFT_TOP,    KC_NO
#define WIN_QAZ40_RAISE_LEFT_MIDDLE   WIN_QAZ_RAISE_LEFT_MIDDLE, KC_NO
#define WIN_QAZ40_RAISE_LEFT_BOTTOM   WIN_QAZ_RAISE_LEFT_BOTTOM, KC_NO

#define WIN_QAZ40_RAISE_RIGHT_TOP     KC_NO, WIN_QAZ_RAISE_RIGHT_TOP
#define WIN_QAZ40_RAISE_RIGHT_MIDDLE  KC_NO, WIN_QAZ_RAISE_RIGHT_MIDDLE
#define WIN_QAZ40_RAISE_RIGHT_BOTTOM  KC_NO, WIN_QAZ_RAISE_RIGHT_BOTTOM

// Layer 6  Win Lower : Symbols
#define WIN_QAZ40_LOWER_LEFT_TOP      WIN_QAZ_LOWER_LEFT_TOP,    KC_NO
#define WIN_QAZ40_LOWER_LEFT_MIDDLE   WIN_QAZ_LOWER_LEFT_MIDDLE, KC_NO
#define WIN_QAZ40_LOWER_LEFT_BOTTOM   WIN_QAZ_LOWER_LEFT_BOTTOM, KC_NO

#define WIN_QAZ40_LOWER_RIGHT_TOP     KC_NO, WIN_QAZ_LOWER_RIGHT_TOP
#define WIN_QAZ40_LOWER_RIGHT_MIDDLE  KC_NO, WIN_QAZ_LOWER_RIGHT_MIDDLE
#define WIN_QAZ40_LOWER_RIGHT_BOTTOM  KC_NO, WIN_QAZ_LOWER_RIGHT_BOTTOM

// Layer 7  Win Adjust : Functions and Mouse
#define WIN_QAZ40_ADJUST_LEFT_TOP     WIN_QAZ_ADJUST_LEFT_TOP,    WIN(CAPTURE_1)
#define WIN_QAZ40_ADJUST_LEFT_MIDDLE  WIN_QAZ_ADJUST_LEFT_MIDDLE, WIN(CAPTURE_2)
#define WIN_QAZ40_ADJUST_LEFT_BOTTOM  WIN_QAZ_ADJUST_LEFT_BOTTOM, WIN(CAPTURE_3)

#define WIN_QAZ40_ADJUST_RIGHT_TOP    KC_NO, WIN_QAZ_ADJUST_RIGHT_TOP
#define WIN_QAZ40_ADJUST_RIGHT_MIDDLE KC_NO, WIN_QAZ_ADJUST_RIGHT_MIDDLE
#define WIN_QAZ40_ADJUST_RIGHT_BOTTOM KC_NO, WIN_QAZ_ADJUST_RIGHT_BOTTOM

// ==========   40% Normal   ==========
// Layer 4  Win Base
#define WIN_NOR40_BASE_LEFT_TOP       KC_TAB,  WIN_QAZ_BASE_LEFT_TOP
#define WIN_NOR40_BASE_LEFT_MIDDLE    KC_LCTL, WIN_QAZ_BASE_LEFT_MIDDLE
#define WIN_NOR40_BASE_LEFT_BOTTOM    KC_LSFT, WIN_QAZ_BASE_LEFT_BOTTOM

#define WIN_NOR40_BASE_RIGHT_TOP      WIN_QAZ_BASE_RIGHT_TOP,    KC_BSPC
#define WIN_NOR40_BASE_RIGHT_MIDDLE   WIN_QAZ_BASE_RIGHT_MIDDLE, KC_ENT
#define WIN_NOR40_BASE_RIGHT_BOTTOM   WIN_QAZ_BASE_RIGHT_BOTTOM, KC_RSFT

// Layer 5  Win Raise : Numbers and Arrows
#define WIN_NOR40_RAISE_LEFT_TOP       KC_TAB,  WIN_QAZ_RAISE_LEFT_TOP
#define WIN_NOR40_RAISE_LEFT_MIDDLE    KC_LCTL, WIN_QAZ_RAISE_LEFT_MIDDLE
#define WIN_NOR40_RAISE_LEFT_BOTTOM    KC_LSFT, WIN_QAZ_RAISE_LEFT_BOTTOM

#define WIN_NOR40_RAISE_RIGHT_TOP      WIN_QAZ_RAISE_RIGHT_TOP,    KC_NO
#define WIN_NOR40_RAISE_RIGHT_MIDDLE   WIN_QAZ_RAISE_RIGHT_MIDDLE, KC_NO
#define WIN_NOR40_RAISE_RIGHT_BOTTOM   WIN_QAZ_RAISE_RIGHT_BOTTOM, KC_NO

// Layer 6  Win Lower : Symbols
#define WIN_NOR40_LOWER_LEFT_TOP       KC_TAB,  WIN_QAZ_LOWER_LEFT_TOP
#define WIN_NOR40_LOWER_LEFT_MIDDLE    KC_LCTL, WIN_QAZ_LOWER_LEFT_MIDDLE
#define WIN_NOR40_LOWER_LEFT_BOTTOM    KC_LSFT, WIN_QAZ_LOWER_LEFT_BOTTOM

#define WIN_NOR40_LOWER_RIGHT_TOP      WIN_QAZ_LOWER_RIGHT_TOP,    KC_NO
#define WIN_NOR40_LOWER_RIGHT_MIDDLE   WIN_QAZ_LOWER_RIGHT_MIDDLE, KC_NO
#define WIN_NOR40_LOWER_RIGHT_BOTTOM   WIN_QAZ_LOWER_RIGHT_BOTTOM, KC_NO

// Layer 7  Win Adjust : Functions and Mouse
#define WIN_NOR40_ADJUST_LEFT_TOP       KC_TAB,  WIN_QAZ_ADJUST_LEFT_TOP
#define WIN_NOR40_ADJUST_LEFT_MIDDLE    KC_LCTL, WIN_QAZ_ADJUST_LEFT_MIDDLE
#define WIN_NOR40_ADJUST_LEFT_BOTTOM    KC_LSFT, WIN_QAZ_ADJUST_LEFT_BOTTOM

#define WIN_NOR40_ADJUST_RIGHT_TOP      WIN_QAZ_ADJUST_RIGHT_TOP,    WIN(CAPTURE_1)
#define WIN_NOR40_ADJUST_RIGHT_MIDDLE   WIN_QAZ_ADJUST_RIGHT_MIDDLE, WIN(CAPTURE_2)
#define WIN_NOR40_ADJUST_RIGHT_BOTTOM   WIN_QAZ_ADJUST_RIGHT_BOTTOM, WIN(CAPTURE_3)


// ==========   Special   ==========
// Layer 8  Special
#define QAZ_NONE        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
#define QAZ40_NONE      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
#define QAZ_NONE_THUMBS KC_NO, KC_NO, KC_NO


// ==========   Encoder   ==========
#define CCW_BASE       MS_WHLD
#define CW_BASE        MS_WHLU
#define CCW_RAISE      LGUI(KC_PMNS)
#define CW_RAISE       LGUI(KC_PPLS)
#define WIN_CCW_RAISE  LCTL(KC_PMNS)
#define WIN_CW_RAISE   LCTL(KC_PPLS)
#define CCW_LOWER      KC_BRID
#define CW_LOWER       KC_BRIU
#define CCW_ADJUST     KC_VOLD
#define CW_ADJUST      KC_VOLU

#define ENCODER_MS_WHEEL {ENCODER_CCW_CW(CCW_BASE, CW_BASE)}
#define ENCODER_MAC_ZOOM {ENCODER_CCW_CW(CCW_RAISE, CW_RAISE)}
#define ENCODER_WIN_ZOOM {ENCODER_CCW_CW(WIN_CCW_RAISE, WIN_CW_RAISE)}
#define ENCODER_BRIGHT   {ENCODER_CCW_CW(CCW_LOWER, CW_LOWER)}
#define ENCODER_VOL      {ENCODER_CCW_CW(CCW_ADJUST, CW_ADJUST)}
#define ENCODER_NO       {ENCODER_CCW_CW(KC_NO, KC_NO)}


// ==========   Combo   ==========
#define COMBO_KEY_MS_ACL0 {MS_BTN1, MS_BTN3, COMBO_END}
#define COMBO_KEY_MS_ACL1 {MS_BTN1, MS_BTN2, COMBO_END}
#define COMBO_KEY_MS_ACL2 {MS_BTN2, MS_BTN3, COMBO_END}
#define COMBO_OUT_MS_ACL0 MS_ACL0
#define COMBO_OUT_MS_ACL1 MS_ACL1
#define COMBO_OUT_MS_ACL2 MS_ACL2
