ENCODER_MAP_ENABLE = yes
CAPS_WORD_ENABLE = yes
OS_DETECTION_ENABLE = yes
CUSTOM_HOLD_ON_OTHER_KEY_PRESS_PER_KEY = yes
CUSTOM_RGBLIGHT = no
CUSTOM_RGBMATRIX = yes
CUSTOM_KEY_OVERRIDE = yes
CUSTOM_COMBO = yes

SRC += km_rgb.c \
	   km_tap_hold.c

