ENCODER_MAP_ENABLE = yes
CAPS_WORD_ENABLE = yes
OS_DETECTION_ENABLE = no
CUSTOM_HOLD_ON_OTHER_KEY_PRESS_PER_KEY = yes
CUSTOM_RGBLIGHT = no
CUSTOM_KEY_OVERRIDE = yes

SRC += my_rgb.c \
	   my_tap_hold.c

